# Generated by Django 4.2.3 on 2023-07-09 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chats", "0003_message_author_message_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="author",
        ),
        migrations.RemoveField(
            model_name="message",
            name="message",
        ),
        migrations.AddField(
            model_name="message",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chats.contact",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="content",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="friends",
            field=models.ManyToManyField(blank=True, null=True, to="chats.contact"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friends",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="chat_room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chats.room",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "messages",
                    models.ManyToManyField(blank=True, null=True, to="chats.message"),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True, null=True, related_name="chats", to="chats.contact"
                    ),
                ),
            ],
        ),
    ]
