# Generated by Django 4.2.3 on 2023-07-10 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0004_remove_message_author_remove_message_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="messages",
            field=models.ManyToManyField(blank=True, to="chats.message"),
        ),
        migrations.AlterField(
            model_name="chat",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="chats", to="chats.contact"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="friends",
            field=models.ManyToManyField(blank=True, to="chats.contact"),
        ),
        migrations.AlterField(
            model_name="message",
            name="chat_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chats.room",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chats.contact",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
