# Generated by Django 4.2.3 on 2023-07-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0005_alter_chat_messages_alter_chat_participants_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
